spring:
  datasource:
    url: ${MYSQLDB_URL:jdbc:mysql://localhost:3306/phonebook_schema}
    username: ${MYSQLDB_USER:root}
    password: ${MYSQLDB_ROOT_PASSWORD:sh7513244}

  jpa:
    hibernate:
      ddl-auto: create
    defer-datasource-initialization: true
  sql:
    init:
      mode: always
server:
  port: 8082
